// <auto-generated />
using System;
using LRS.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LRS.Infrastructure.Migrations
{
    [DbContext(typeof(LrsDbContext))]
    [Migration("20260108200515_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LRS.Domain.Entities.AdministrativeSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AdministrativeSourceTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AdministrativeSourceTypeId");

                    b.ToTable("AdministrativeSources");
                });

            modelBuilder.Entity("LRS.Domain.Entities.AdministrativeSourceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AmharicValue")
                        .HasColumnType("text");

                    b.Property<string>("EnglishValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HarariValue")
                        .HasColumnType("text");

                    b.Property<string>("OromoValue")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AdministrativeSourceTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EnglishValue = "Title Certificate"
                        },
                        new
                        {
                            Id = 2,
                            EnglishValue = "Tax Receipt"
                        },
                        new
                        {
                            Id = 3,
                            EnglishValue = "Injunction registration Letter"
                        });
                });

            modelBuilder.Entity("LRS.Domain.Entities.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdministrativeSourceId")
                        .HasColumnType("integer");

                    b.Property<string>("AppRegId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("DocumentName")
                        .HasColumnType("text");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<int>("SourceId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UniqueParcelId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AdministrativeSourceId");

                    b.HasIndex("SourceId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("LRS.Domain.Entities.Source", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCreated")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime>("RecordationDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Sources");
                });

            modelBuilder.Entity("LRS.Domain.Entities.AdministrativeSource", b =>
                {
                    b.HasOne("LRS.Domain.Entities.AdministrativeSourceType", "AdministrativeSourceType")
                        .WithMany()
                        .HasForeignKey("AdministrativeSourceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdministrativeSourceType");
                });

            modelBuilder.Entity("LRS.Domain.Entities.Document", b =>
                {
                    b.HasOne("LRS.Domain.Entities.AdministrativeSource", "AdministrativeSource")
                        .WithMany()
                        .HasForeignKey("AdministrativeSourceId");

                    b.HasOne("LRS.Domain.Entities.Source", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdministrativeSource");

                    b.Navigation("Source");
                });
#pragma warning restore 612, 618
        }
    }
}
