// <auto-generated />
using System;
using LRS.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LRS.Infrastructure.Migrations
{
    [DbContext(typeof(LrsDbContext))]
    partial class LrsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LRS.Domain.Entities.AdministrativeSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AdministrativeSourceTypeId")
                        .HasColumnType("integer");

                    b.Property<int?>("ApplicationId")
                        .HasColumnType("integer");

                    b.Property<int?>("BaUnitId")
                        .HasColumnType("integer");

                    b.Property<int>("SourceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AdministrativeSourceTypeId");

                    b.HasIndex("SourceId")
                        .IsUnique();

                    b.ToTable("AdministrativeSources");
                });

            modelBuilder.Entity("LRS.Domain.Entities.AdministrativeSourceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AmharicValue")
                        .HasColumnType("text");

                    b.Property<string>("EnglishValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HarariValue")
                        .HasColumnType("text");

                    b.Property<string>("OromifaValue")
                        .HasColumnType("text");

                    b.Property<string>("TigrinyaValue")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AdministrativeSourceTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AmharicValue = "የይዞታ ማረጋገጫ ሰርተፊኬት",
                            EnglishValue = "Title Certificate",
                            OromifaValue = "Waraqaa ragaa eenyummaa mirkaneessu"
                        },
                        new
                        {
                            Id = 2,
                            AmharicValue = "የመሬት ግብር ክፍያ ደረሰኝ",
                            EnglishValue = "Tax Receipt",
                            OromifaValue = "Waraqaa Kaffaltii Gibiraa"
                        },
                        new
                        {
                            Id = 3,
                            AmharicValue = "የእግድ ደብዳቤ",
                            EnglishValue = "Injunction registration Letter",
                            OromifaValue = "Xalayaa Dhoorkii Mana Murtii"
                        },
                        new
                        {
                            Id = 4,
                            AmharicValue = "የእግድ ስረዛ ደብዳቤ",
                            EnglishValue = "Injunction release Letter",
                            OromifaValue = "Xalayaa Dhoorkii Mana Murtii Kaasu"
                        },
                        new
                        {
                            Id = 5,
                            AmharicValue = "የዕዳ ምዝገባ ደብዳቤ",
                            EnglishValue = "Mortgage registration letter",
                            OromifaValue = "Xalayaa Dhoorkii Baankii"
                        },
                        new
                        {
                            Id = 6,
                            AmharicValue = "የዕዳ ስረዛ ደብዳቤ",
                            EnglishValue = "Mortgage registration release",
                            OromifaValue = "Xalayaa Dhoorkii Baankii Kaasu"
                        },
                        new
                        {
                            Id = 7,
                            AmharicValue = "የከፊል ሽያጭ ውል ሰነድ",
                            EnglishValue = "Partial Sale Contract",
                            OromifaValue = "Galmee Waliigaltee Walakkaa Gurgurtaa"
                        });
                });

            modelBuilder.Entity("LRS.Domain.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LRS.Domain.Entities.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AlfDocumentId")
                        .HasColumnType("text");

                    b.Property<string>("AppRegId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("DocumentName")
                        .HasColumnType("text");

                    b.Property<bool>("IsVoid")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("text");

                    b.Property<int?>("SourceId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SubmissionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UniqueParcelId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SourceId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("LRS.Domain.Entities.FidoCredential", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("AaGuid")
                        .HasColumnType("uuid");

                    b.Property<int>("AppUserId")
                        .HasColumnType("integer");

                    b.Property<int>("CredType")
                        .HasColumnType("integer");

                    b.Property<byte[]>("CredentialId")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PublicKey")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("RegDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("SignatureCounter")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("UserHandle")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("FidoCredentials");
                });

            modelBuilder.Entity("LRS.Domain.Entities.Source", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCreated")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("RecordationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Sources");
                });

            modelBuilder.Entity("LRS.Domain.Entities.AdministrativeSource", b =>
                {
                    b.HasOne("LRS.Domain.Entities.AdministrativeSourceType", "AdministrativeSourceType")
                        .WithMany()
                        .HasForeignKey("AdministrativeSourceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LRS.Domain.Entities.Source", null)
                        .WithOne("AdministrativeSource")
                        .HasForeignKey("LRS.Domain.Entities.AdministrativeSource", "SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdministrativeSourceType");
                });

            modelBuilder.Entity("LRS.Domain.Entities.Document", b =>
                {
                    b.HasOne("LRS.Domain.Entities.Source", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("LRS.Domain.Entities.FidoCredential", b =>
                {
                    b.HasOne("LRS.Domain.Entities.AppUser", "AppUser")
                        .WithMany("FidoCredentials")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("LRS.Domain.Entities.AppUser", b =>
                {
                    b.Navigation("FidoCredentials");
                });

            modelBuilder.Entity("LRS.Domain.Entities.Source", b =>
                {
                    b.Navigation("AdministrativeSource");
                });
#pragma warning restore 612, 618
        }
    }
}
